version: "3.9"

services:
  android:
    container_name: android_ultra_light
    image: budtmo/docker-android-arm64:13.0
    privileged: true
    ports:
      - "6080:6080"
      - "5555:5555"
    environment:
      DEVICE: "Nexus 5"
      EMULATOR: "true"
      DISABLE_HW_ACCELERATION: "true"
      WEB_VNC: "true"
      VNC_PASSWORD: "Clown80990@"
    volumes:
      - android_data:/data

volumes:
  android_data:
